### ISSUE TITLE
Passing backend options

### ISSUE THREAD

**Issue by hakanyi** [ayushnix/tessen#12]
Great project, thank you! 
I've been trying to add an option to the `rofi` backend, for example, a font:
```bash
tessen -b 'rofi -dmenu -i -font "Roboto 11"'
```
but that doesn't seem to work. It'd be great to pass a font and a theme etc. Any ideas? Thanks!

**Comment by ayushnix** [comment]
@t0fik

**Comment by ayushnix** [comment]
@hakanyi Hi, thank you for raising this bug report.

`rofi` is supported by tessen by default so you can use

```sh
tessen -b rofi
```

to use rofi. If you want to change the font of rofi, you can create/edit `~/.config/rofi/config.rasi` and mention a font in that file.

I didn't think about the issue of accepting arbitrary input as argument when I merged #9. Let me think about what I can do here. You can use the solution I've suggested in the meantime.

**Comment by ayushnix** [comment]
@hakanyi A new version of tessen has been released and it supports configuring rofi using a configuration file. This should solve your issue.

If there's anything else, let me know and I'll reopen this issue.

**Comment by e-tho** [comment]
@ayushnix  Passing arguments to the backend could still be beneficial in situations where you need to overwrite certain parameters set in the main configuration file. Like changing the prompt, for example.
