### ISSUE TITLE
Feature request: support for smartcards/yubikey

### ISSUE THREAD

**Issue by Sohex** [ayushnix/tessen#22]
I have gopass setup to use a gpg key that lives on my yubikey. This works fine with tessen as well, except for when I need to use a password to unlock it. Where gopass would normally prompt me with pinentry tessen doesn't generate any kind of prompt at all. This means I have to go enter the pin elsewhere to unlock the yubikey before I can use tessen. Ideally tessen would pop up with a pinentry window when it's necessary.

**Comment by ayushnix** [comment]
Unfortunately, I don't have a yubikey to test and determine if this is something that tessen needs to fix. 

Normally, if the gpg password isn't in gpg-agent, if you use tessen, the pinentry menu does come up and asks for your password. From what you've described, it looks like gopass uses a pinentry prompt to unlock the yubikey? Without a yubikey to test things myself, I don't think I'll be able to do anything about this.

If you can open a PR to fix this issue, I'd be happy to review it.

**Comment by krevedkokun** [comment]
it works for me

**Comment by so-rose** [comment]
@Sohex Tessen merely invokes pass, which in turn merely invokes gpg, which in turn calls gpg-agent which delegates getting a pin from the user to a sensible installed pinentry.

If you only have a TUI pinentry like pinentry-curses installed, then seemingly nothing will happen when a GUI program like tessen or rofi-pass asks for a password, which requires a PIN to unlock the smartcard. If the smartcard has already been unlocked by running the pinentry from the terminal, tessen's `pass` call doesn't require a PIN.

The good news is, all you need is a GUI pinentry. The easiest way is something like pinentry-gnome3, which you can also set in your gpg-agent.conf (https://wiki.archlinux.org/title/GnuPG#pinentry) to force its usage.

**Comment by ayushnix** [comment]
@so-rose Thanks for confirming that hardware keys work as expected when using `tessen`.

@Sohex Are you still facing this issue? Are you using a GUI pinentry like `pinentry-qt` or `pinentry-gnome3` in `~/.gnupg/gpg-agent.conf`?

**Comment by Sohex** [comment]
Apologies, this was an issue with my pinentry configuration, closing.
