### ISSUE TITLE
Using `-a autotype` or `action=autotype` in config doesn't work as expected

### ISSUE THREAD

**Issue by amenonsen** [ayushnix/tessen#25]
Because the script explicitly assigns `tsn_action="default"` near the start, but later checks `-z $tsn_action` before changing the value, the value always remains "default", and both autotype and copy are always offered. Just commenting out the default assignment fixes the problem for me.

Thanks for the nice script.

**Comment by ayushnix** [comment]
@amenonsen thanks for raising this bug report, v2.1.2 should've fixed it
