### ISSUE TITLE
Notification mentions "username" no matter what the field you copy

### ISSUE THREAD

**Issue by somini** [ayushnix/tessen#27]
https://github.com/ayushnix/tessen/blob/master/tessen#L457

According to the field you copy, this should be reflected on the notification text.

At first I though I was doing something wrong, and the username was always being copied.

---

Thanks for providing a Wayland alternative to `rofi-pass`, much appreciated.

**Comment by ayushnix** [comment]
Oops 😅 

I think I'll just change the text to `data has been copied and will be cleared from the clipboard after $tsn_cliptime seconds`. Although mentioning the name of the field being copied would be nice, it might be seen as leaking unnecessary metadata.
