### ISSUE TITLE
ignore spaces

### ISSUE THREAD

**Issue by sambaccessnow** [ayushnix/tessen#31]
thaks for writing tessen

I'm using tessen with wofi and when I'm searching for password I use multiple char separated by spaces to select the password I'm looking for

Unfortunatelly tessen is not ignoring spaces and is looking for it so I can't find my password unless I know the exact path location

is it possible for tessen to ignore spaces ?

**Comment by ayushnix** [comment]
I haven't received a response. I'm closing this ticket for now. Let me know if you're still facing issues with other dmenu programs.
