### ISSUE TITLE
filename used for username, not key

### ISSUE THREAD

**Issue by UltraBlackLinux** [ayushnix/tessen#52]
Hey there,
I really like this project overall, but there's one problem that's bugging me: I cannot get tessen to use `login` or `username` as the username value. 
I added a regex pattern for the username value and it's still using the filename for the username.
My `~/.config/tessen/config`:
```
dmenu_backend="fuzzel"
action="autotype"
delay="100"
notify="true"
userkey="(user.*|login)"
```
Any idea why that is happening?

**Comment by ayushnix** [comment]
should be fixed with the latest release

let me know if you still face any issues

**Comment by ayushnix** [comment]
should work now

**Comment by UltraBlackLinux** [comment]
yes it's working, thank you so much!
