### ISSUE TITLE
Remove checking for oathtool?

### ISSUE THREAD

**Issue by amnore** [ayushnix/tessen#6]
Hi, I found this program to replace rofi-pass when using sway, and it works great!

However, I have some issues with otp. The reason is that I'm using NixOS, where all packaged are located in `/nix/store/<some hashed path>`, and oathtool is not in my PATH. Pass-otp is patched to use absolute path of oathtool, but tessen checks for oathtool and doesn't find it. So it displays an error after selecting otp.

I think checking for oathtool may not be necessary? Since the user already has pass-otp, you can assume that its dependencies are already taken care of.

**Comment by ayushnix** [comment]
Makes sense, I'm not sure why I decided to check for the presence of `oathtool` considering it's listed as a dependency of `pass-otp`.

**Comment by ayushnix** [comment]
Thanks for the report.

Fixed in [v1.2.3](https://github.com/ayushnix/tessen/releases/tag/v1.2.3)
